apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-mana
  labels:
    purpose: "mana"
spec:
  capacity:
    storage: 50Mi
  volumeMode: Filesystem
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/opt/aether/logs-mana"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-mana
spec:
  selector:
    matchLabels:
      purpose: "mana"
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
