apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-mana
  labels:
    purpose: "mana"
    database: "postgresql"
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/opt/aether/data-mana"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-mana
spec:
  selector:
    matchLabels:
      purpose: "mana"
      database: "postgresql"
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
